RealEestateSystem/Controllers/AgentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstateSystem.Models.ViewModels.Agents;
using RealEstateSystem.Services.Data.Interfaces;
using RealEstateSystems.Web.Infrastructure.Extensions;



namespace RealEstateSystem.Controllers
{
    [Authorize]
    public class AgentController : Controller
    {

        private readonly IAgentInterface agentInterface;

        private readonly IUserInterface userInterface;

        public AgentController(IAgentInterface agentInterface,IUserInterface userInterface)
        {
            this.agentInterface = agentInterface;
            this.userInterface = userInterface;
        }
       
        public async Task <IActionResult> Become()
        {

            var userId = this.User.GetId();

            if (userId != null)
            {
                var isAgent = await this.agentInterface.ExistById(Guid.Parse(userId));

                if (isAgent)
                {
                    return View("Agent Error", "There was an error processing your request as a dealer.");
                }


            }

            return View();
        }

        [HttpPost]        
        public async Task <IActionResult> BecomeAgent(BecomeAgentFormModel becomeAgent)
        {


            var userId = this.User.GetId();

            if (userId != null)
            {
                var isAgent = await this.agentInterface.ExistById(Guid.Parse(userId));

                if (isAgent)
                {
                    return View("Agent Error", "There was an error processing your request as a dealer.");
                }


            }
            
            if (await agentInterface.ExistAgentByPhoneNumber(becomeAgent.PhoneNumber))
            {
                ModelState.AddModelError(nameof(becomeAgent.PhoneNumber), "This phone number is already in use. Enter another one. ");
            }

            if (await userInterface.UserHasRent(Guid.Parse(userId)))
            {
                ModelState.AddModelError("Error","You can't be a dealer because you have a rent.");
            }
            

            if (!ModelState.IsValid)
            {
                return View(nameof(Become));
            }

            await agentInterface.Create(Guid.Parse(userId),becomeAgent);

            TempData["Message"] = "You have successfully applied to become a agent.";

            return RedirectToAction("All", "House"); 
            


        }


    }
}

RealEestateSystem/Views/Agent/Become.cshtml
@using RealEstateSystem.Models.ViewModels.Agents;
@model BecomeAgentFormModel


@{
ViewBag.Title = "Become Agent";    

}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewData.ModelState?["Error"]?.Errors.First().ErrorMessage
    </div>
}
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post" asp-controller="Agent" asp-action="BecomeAgent">
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control"
                       placeholder="+4988888888888">
                <span asp-validation-for="PhoneNumber" class="small text-danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3 " type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}