RealEestateSystem/Areas/Admin/Controllers/HouseController.cs
using Microsoft.AspNetCore.Mvc;
using RealEstateSystem.Areas.Admin.Models.House;
using RealEstateSystem.Services.Data.Interfaces;
using RealEstateSystems.Web.Infrastructure.Extensions;


namespace RealEstateSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HouseController:BaseAdminController
    {
        private readonly IHouseInterface _houseInterface;

        private readonly IAgentInterface _agentInterface;

        public HouseController(IHouseInterface houseInterface, IAgentInterface agentInterface)
        {
            _houseInterface = houseInterface;
            _agentInterface = agentInterface;
        }        


        public async Task<IActionResult> MineHouse()
        {
            var myHouses = new MyHousesViewModel();
            
            var userIdString =  User.GetId();
            var adminUserId = Guid.Parse(userIdString);
            myHouses.RentedHouses = await _houseInterface.GetAllHouseByUserId(adminUserId);

            string adminAgentId = await _agentInterface.GetAgentId(adminUserId);
            var adminAgent= Guid.Parse(adminAgentId);
            myHouses.AddedHouses = await _houseInterface.GetAllHouseByAgentId(adminAgent);

            return View(myHouses);
        }


    }
}

RealEestateSystem/Areas/Admin/Controllers/RentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using RealEstateSystem.Models.ViewModels.Rent;
using RealEstateSystem.Services.Data.Interfaces;
using RealEstateSystems.Web.Infrastructure.Helper;
using static RealEstateSystem.Areas.Admin.AdminConstants;

namespace RealEstateSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RentController : BaseAdminController
    {

        private readonly IRentInterface _rentInterface;

        private readonly IMemoryCache _cache;

        private readonly GetImageFromDbDecoding getImage;

        public RentController(IRentInterface rentInterface,GetImageFromDbDecoding getImage,IMemoryCache cache)
        {
            _rentInterface = rentInterface;
            _cache = cache;
            this.getImage = getImage;
        }

        [HttpGet]
        [Route("Admin/Rent/All")]
        public async Task <IActionResult> All()
        {

            var rents = _cache.Get<IEnumerable<RentServiceViewModel>>(RentCacheKey);

            if (rents == null)
            {
                rents = await _rentInterface.All();
                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(5));
                _cache.Set(RentCacheKey, rents, cacheEntryOptions);
            }           
            

            foreach (var rent in rents)
            {
                rent.ImageData = getImage.GetImageAsync(rent.ImageId).Result;
            }       

            return View(rents);
            
        }
    }
}

RealEestateSystem/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using RealEstateSystem.Models.ViewModels.User;
using RealEstateSystem.Services.Data.Interfaces;
using static RealEstateSystem.Areas.Admin.AdminConstants;

namespace RealEstateSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : BaseAdminController
    {

        private readonly IUserInterface _userInterface;
        private readonly IMemoryCache _cache;

        public UserController(IUserInterface userInterface,IMemoryCache cache)
        {
            _userInterface = userInterface;
            _cache = cache;
        }

        [HttpGet]
        [Route("Admin/User/All")]
        public async Task<IActionResult> All()
        {
            var users= _cache.Get<IEnumerable<UserServiceViewModel>>(UserCacheKey); 

            if (users == null)
            {
                users = await _userInterface.All();
                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(5));
                _cache.Set(UserCacheKey, users, cacheEntryOptions);
            }            

            return View(users);
        }
    }
}

RealEestateSystem/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@inject IAgentInterface agentInterface

@{  
    var userId = User.GetId();

    bool isAgent = false;

    if (!string.IsNullOrEmpty(userId))
    {
        isAgent = agentInterface.ExistById(new Guid(userId)).Result;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Best Real Estate System</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RealEstateSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RealEstateSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item dropdown">
                            <div>
                                <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">All</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li>
                                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="House" asp-action="All">All Houses</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="Rent" asp-action="All">All Rents</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="All">All Users</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="AllCategory">All Categories</a>
                                    </li>
                                </ul>
                            </div>
                        </li>


                        

                        @if (User.Identity!=null&& User.Identity.IsAuthenticated) 
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="MineHouse">My Houses</a>
                            </li>

                            @if (isAgent)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Add">Add Houses</a>
                                </li>
                            }
                            

                            
                        }                       
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @if (TempData["Message"] != null)
            {
            <div class="alert alert-success allert-dismissible fade show" role="alert">
                @TempData["Message"]

                <button type="button" class="btn-close" data-bs-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            }

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - RealEstateSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>   
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>